name: stagingKubeEnvironment
type: resource.environment
driver: kube
description: Environment variables for the staging environment
provides:
  - type: environment.properties
    name: dbEnvProps
    description: Database properties
    params:
      - name: db_port
        value: 5432
      - name: db_host
        value: chartersdb-service
      - name: db_name
        value: charters
      - name: db_use_ssl
        value: 'false'
  - type: environment.properties
    name: appEnvProps
    description: Application Properties
    params:
      - name: welcome_port
        value: 3000
      - name: charters_port
        value: 3001
      - name: charters_host
        value: chartersms-service
      - name: reservations_port
        value: 3003
      - name: reservations_host
        value: reservationsms-service
      - name: app_message
        value: 'Hello from Rezolvr!'
  - type: environment.properties
    name: registryProps
    description: Staging environment registry properties
    params:
      - name: endpoint
        value: host.minikube.internal:5000/
uses: # This is really ".Platform"
  - type: platform.settings
    name: default
    params:
      - name: numInstances
        value: 1
      - name: imagePullPolicy
        value: Always
      - name: serviceType
        value: NodePort
  - type: platform.settings
    name: chartersdb
    params:
      - name: numInstances
        value: 1
      - name: serviceType
        value: ClusterIP
  - type: platform.settings
    name: reservationsdb
    params:
      - name: isExternal
        value: true
  - type: platform.settings
    name: chartersms
    params:
      - name: nodePort
        value: 30163
  - type: platform.settings
    name: reservationsms
    params:
      - name: nodePort
        value: 30164
  - type: platform.settings
    name: welcomeapp
    params:
      - name: nodePort
        value: 30165
