name: stagingKubeEnvironment
type: resource.environment
driver: kube
description: Environment variables for the staging environment
provides:
  - type: environment.properties
    name: dbEnvProps
    description: Database properties
    params:
      - name: db_username
        value: staginguser
      - name: db_password
        value: passwordie
      - name: db_port
        value: 5432
      - name: db_host
        value: catalogdb-service
  - type: environment.properties
    name: appEnvProps
    description: Application Properties
    params:
      - name: welcome_port
        value: 3000
      - name: catalog_port
        value: 3001
      - name: catalog_host
        value: catalogms-service
      - name: orders_port
        value: 3003
      - name: orders_host
        value: ordersms-service
      - name: app_message
        value: 'Hello from Rezolvr!'
  - type: environment.properties
    name: registryProps
    description: Staging environment registry properties
    params:
      - name: endpoint
        value: host.minikube.internal:5000/
uses: # This is really ".Platform"
  - type: platform.settings
    name: default
    params:
      - name: numInstances
        value: 1
      - name: imagePullPolicy
        value: Always
      - name: serviceType
        value: NodePort
  - type: platform.settings
    name: catalogdb
    params:
      - name: numInstances
        value: 1
      - name: serviceType
        value: ClusterIP
  - type: platform.settings
    name: ordersdb
    params:
      - name: isExternal
        value: true
  - type: platform.settings
    name: catalogms
    params:
      - name: nodePort
        value: 30163
  - type: platform.settings
    name: ordersms
    params:
      - name: nodePort
        value: 30164
  - type: platform.settings
    name: welcomeapp
    params:
      - name: nodePort
        value: 30165
