apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: catalogdb
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: catalogdb
          image: postgres
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: 'catalog'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: databaseCredentials
                key: db_password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: databaseCredentials
                key: db_username
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
  namespace: default
  labels:
    app: postgresdb
spec:
  type: ClusterIP
  selector:
    app: catalogdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      
