apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: mydb
  replicas: 1
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: mydb
          image: postgres 
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: passwordie
          - name: POSTGRES_USER
            value: abetterusername 
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  namespace: default
  labels:
    app: postgresdb
spec:
  type: ClusterIP
  selector:
    app: mydb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
