apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders_service
  replicas: 1
  template:
    metadata:
      labels:
        app: orders_service
    spec:
      containers:
        - name: orders_service
          image: orders
          imagePullPolicy: Never 
          ports:
          - containerPort: 3003
          env:
          - name: DB_HOST
            value: 'catalogdb-service'
          - name: DB_NAME
            value: 'postgres'
          - name: DB_PORT
            value: '5432'
          - name: DB_PW
            value: 'passwordie'
          - name: DB_USER
            value: 'staginguser'
          - name: MY_PORT
            value: '3003' 
---
apiVersion: v1
kind: Service
metadata:
  name: orders_service-service
  namespace: default
  labels:
    app: orders
spec:
  type: NodePort
  selector:
    app: orders_service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30163
