apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  selector:
    matchLabels:
      app: welcomeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: welcomeapp
    spec:
      containers:
        - name: welcomeapp
          image: host.minikube.internal:5000/welcome
          imagePullPolicy: Always 
          ports:
          - containerPort: 3000
          env:
          - name: APP_MSG
            value: 'Hello from Rezolvr!'
          - name: CHARTERS_URL
            value: 'catalogms-service:3001/charters'
          - name: ORDERS_URL
            value: 'ordersms-service:3003/orders'
          - name: WELCOME_PORT
            value: '3000' 
---
apiVersion: v1
kind: Service
metadata:
  name: welcomeapp-service
  namespace: default
  labels:
    app: welcome
spec:
  type: NodePort
  selector:
    app: welcomeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30165
