apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
spec:
  selector:
    matchLabels:
      app: reservationsms
  replicas: 1
  template:
    metadata:
      labels:
        app: reservationsms
    spec:
      containers:
        - name: reservationsms
          image: host.minikube.internal:5000/reservations
          imagePullPolicy: Always
          ports:
          - containerPort: 3003
          env:
          - name: DB_HOST
            value: 'chartersdb-service'
          - name: DB_NAME
            value: 'postgres'
          - name: DB_PORT
            value: '5432'
          - name: DB_USE_SSL
            value: 'false'
          - name: MY_PORT
            value: '3003'
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: databasecredentials
                key: db_password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: databasecredentials
                key: db_username
---
apiVersion: v1
kind: Service
metadata:
  name: reservationsms-service
  namespace: default
  labels:
    app: reservations
spec:
  type: NodePort
  selector:
    app: reservationsms
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30164
